// <auto-generated />
using System;
using AI.FrameVue.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AI.FrameVue.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AI.FrameVue.Models.CatalogArtPrint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiMood")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiStyle")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiSubjectTags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorTemperature")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImageAnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ImageHeightIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ImageWidthIn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNewRelease")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Medium")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColorHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColorName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RetailPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryColorHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryColorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectMatter")
                        .HasColumnType("TEXT");

                    b.Property<string>("TertiaryColorHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("TertiaryColorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VendorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WholesaleCost")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AiMood");

                    b.HasIndex("AiStyle");

                    b.HasIndex("Artist");

                    b.HasIndex("ColorTemperature");

                    b.HasIndex("Genre");

                    b.HasIndex("ItemNumber");

                    b.HasIndex("Orientation");

                    b.HasIndex("PrimaryColorHex");

                    b.HasIndex("Style");

                    b.HasIndex("VendorId");

                    b.ToTable("ArtPrints");
                });

            modelBuilder.Entity("AI.FrameVue.Models.CatalogArtPrintVendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageBaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePathPattern")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ArtPrintVendors");
                });

            modelBuilder.Entity("AI.FrameVue.Models.CatalogMat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorTemperature")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Height")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ImageAnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOverSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerItemName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlyCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryColorHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryColorHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryColorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Upc")
                        .HasColumnType("TEXT");

                    b.Property<int>("VendorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ColorCategory");

                    b.HasIndex("ItemName");

                    b.HasIndex("MatClass");

                    b.HasIndex("Material");

                    b.HasIndex("PrimaryColorHex");

                    b.HasIndex("VendorId");

                    b.ToTable("CatalogMats");
                });

            modelBuilder.Entity("AI.FrameVue.Models.CatalogMoulding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ChopCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorCategorySub")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorTemperature")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImageAnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBoxer")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsClosedCorner")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFillet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLiner")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReadyMade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("JoinCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LengthCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("LineName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerItemName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("MouldingHeight")
                        .HasColumnType("REAL");

                    b.Property<string>("MouldingType")
                        .HasColumnType("TEXT");

                    b.Property<double>("MouldingWidth")
                        .HasColumnType("REAL");

                    b.Property<string>("PrimaryColorHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("RabbitHeight")
                        .HasColumnType("REAL");

                    b.Property<double?>("RabbitWidth")
                        .HasColumnType("REAL");

                    b.Property<string>("SecondaryColorHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryColorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Upc")
                        .HasColumnType("TEXT");

                    b.Property<int>("VendorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ColorCategory");

                    b.HasIndex("ItemName");

                    b.HasIndex("Material");

                    b.HasIndex("PrimaryColorHex");

                    b.HasIndex("Profile");

                    b.HasIndex("Style");

                    b.HasIndex("VendorId");

                    b.ToTable("CatalogMouldings");
                });

            modelBuilder.Entity("AI.FrameVue.Models.CatalogVendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMatVendor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMouldingVendor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LifesaverAbbr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Prefix");

                    b.ToTable("CatalogVendors");
                });

            modelBuilder.Entity("AI.FrameVue.Models.DesignFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MouldingDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StyleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserComment")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasChosen")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("AI.FrameVue.Models.DesignOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DesignSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MouldingDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MouldingVendor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StyleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasChosen")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DesignSessionId");

                    b.ToTable("DesignOptions");
                });

            modelBuilder.Entity("AI.FrameVue.Models.DesignSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorTemperature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DominantColorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectMatter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserContext")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DesignSessions");
                });

            modelBuilder.Entity("AI.FrameVue.Models.RoomSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorTemperature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesignStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FurnitureStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecommendedPrintCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomColorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserHintDesignStyle")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserHintRoomType")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserHintWallColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("WallColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WallSpace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoomSessions");
                });

            modelBuilder.Entity("AI.FrameVue.Models.DesignOption", b =>
                {
                    b.HasOne("AI.FrameVue.Models.DesignSession", null)
                        .WithMany("Options")
                        .HasForeignKey("DesignSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AI.FrameVue.Models.DesignSession", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
